### ISSUE TITLE
[v0.4] Добавить инструкции по переносу с других сервисов

### ISSUE THREAD

**Issue by mewforest** [mewforest/vk-music-import#10]
Добавить сервисы или описания:
- [x] Яндекс Музыка ([расширение](https://chrome.google.com/webstore/detail/yamutools-%D0%BD%D0%BE%D0%B2%D1%8B%D0%B5-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8-%D0%B4/dgjneghdfaeajjemeklgmbojeeplehah), треклист)
- [x] YouTube Музыка (https://yt.spotya.ru/)
- [x] СберЗвук (?)
- [x] Apple Music (https://www.idownloadblog.com/2020/10/30/import-export-playlist-apple-music-mac/ ?)
- [x] Deezer, Amazon и прочие ([TuneMyMusic](https://www.tunemymusic.com/ru/), [Soundiiz](https://soundiiz.com/))
- [x] Файлы (m3u, m3u8)

**Comment by Diva206max** [comment]
Жду обнову
