### ISSUE TITLE
[Проблема]

### ISSUE THREAD

**Issue by zargpg74** [mewforest/vk-music-import#11]
Добрый день. Программа и правда переносит треки, однако почему то по два сразу. То есть каждый трек дублируется. 

Windows 11
Любой плейлист
Готовый релиз
V 0.3

**Технические данные (пожалуйста, заполните следующую информацию):**
 - ОС [например, Windows 11]
 - Содержимое файла настроек (`.env`)
 - Ссылка на плейлист
 - Ссылка на профиль ВКонтакте
 - Запускали ли вы готовый релиз (или использовали Python)?
 - Версия программы [например, 0.1]

**Дополнительная информация**
Добавьте сюда дополнительные данные, касающийся проблемы.

**Comment by mewforest** [comment]
Спасибо за репорт! Сегодня выложу исправление, в качестве временного решения проблемы можете использовать v0.2.
Ответил более подробно в #8

**Comment by mewforest** [comment]
Duplicate of #8
