### ISSUE TITLE
[Проблема и ее решение]

### ISSUE THREAD

**Issue by Yamkuo** [mewforest/vk-music-import#13]
**Опишите проблему**
Не находил версию onnxruntime~=1.11.0 и команда "python vk-music-import.py" не работала

**Как воспроизвести ошибку**
pip install -r requirements.txt

**Скриншоты**
До (при изначальной версии onnxruntime~=1.11.0):
![before](https://user-images.githubusercontent.com/122639378/212398349-a054e31b-891e-468a-bdac-eb526c06d566.png)
До (после изменения версии onnxruntime~=1.12.0):
![after](https://user-images.githubusercontent.com/122639378/212398342-6bc63074-9bac-45f9-9bdc-c3a12590954d.png)

**Технические данные:**
 - ОС - Windows 10
 - Ссылка на профиль ВКонтакте - https://vk.com/yamkuo

**Решение проблемы**
Изменил в файле "requirements.txt" строчку с "onnxruntime~=1.11.0" на "onnxruntime~=1.12.0" и проблема решилась

upd. Прошу прощения за какую-либо неясность, если захочешь что-то уточнить, то можешь отписать мне в вк ;). Буду только рад!

**Comment by mewforest** [comment]
Спасибо, что сообщили об устаревших зависимостях, сделал сейчас их более гибкими на случай, если ещё какая-нибудь библиотека захочет удалить старые версии с pip.
