### ISSUE TITLE
[Новая фича] Добавление в плейлист группы

### ISSUE THREAD

**Issue by greyxp** [mewforest/vk-music-import#15]
Хотелось бы иметь возможность экспорта в плейлист группы, а не личные аудио

**Comment by mewforest** [comment]
Добрый вечер! Хорошая фишка, могу добавить в следующем релизе, как будет время.

**Comment by greyxp** [comment]
Будет очень круто и полезно, надеюсь добавите 🙏

**Comment by mewforest** [comment]
Утилита сейчас работает в режиме as-is (как есть), поддержка новых фичей, к сожалению, больше не планируется. 
Если есть базовые знания Python, добавление в аудизаписи группы можно докрутить самостоятельно, поменяв `owner_id` [в этой строчке](https://github.com/mewforest/vk-music-import/blob/main/vk-music-import.py#L419) на id вашей группы.

Например, если было:
```python
self.playlist_response = vk_session.method("audio.createPlaylist", {
    "owner_id": user_info['id'],
    "title": title_playlist
})
```
То станет:
```python
self.playlist_response = vk_session.method("audio.createPlaylist", {
    "owner_id": "12345678",
    "title": title_playlist
})
```

Где `12345678` - id вашей группы.
