### ISSUE TITLE
[Новая фича] Обновление старого плейлиста

### ISSUE THREAD

**Issue by greyxp** [mewforest/vk-music-import#16]
Было бы очень удобно, если бы при наличии в вк плейлиста с таким же названием как импортируемый, не создавался новый плейлист, а полностью обновлялся старый. Это очень помогло бы поддерживать актуальность плейлистов у которых уже есть слушатели.

**Comment by mewforest** [comment]
В рамках текущего VK API, к сожалению, невозможно. Пробовал добавить [audio.getPlaylistById](https://github.com/mewforest/vk-music-import/blob/d3095eceb488de9b154c21e1d804cb5173eafa33/vk-music-import.py#L362) - не возвращает список треков. Ну и [HTML-парсинг](https://github.com/mewforest/vk-music-import/blob/d3095eceb488de9b154c21e1d804cb5173eafa33/vk-music-import.py#L380) без авторизации тоже не помог, ожидаю решения.
