### ISSUE TITLE
[Новая фича] Добавление более 1000 треков в плейлист

### ISSUE THREAD

**Issue by greyxp** [mewforest/vk-music-import#17]
Заметил что при ручном добавлении в плейлист через браузер на десктопе, можно добавить более 1000 треков, видел плейлисты даже на 5к треков. Не подскажете, почему так? И какой на самом деле лимит. Может быть есть возможность использовать это в вашем софте и добавлять больше 1000 треков.

**Comment by mewforest** [comment]
Привет! На момент создания утилиты, API ВКонтакте не умел добавлять в плейлист более 1000 треков, в связи с этим и есть такое ограничение.

Если запускаете модуль с помощью Python, вы можете попробовать обойти это ограничение и посмотреть на результат, для этого измените 1000 на любое другое число, например, на 10000 в данной строчке:

```python
chucked_rows = list(chunks(tracklist, 1000))
```

Если ошибок не будет и плейлист создастся, дайте знать, я обновлю скрипт.

**Comment by hcvbg** [comment]
а как это все запустить?

**Comment by mewforest** [comment]
> а как это все запустить?

Скачать из [релизов](https://github.com/mewforest/vk-music-import/releases/), разархивировать и запустить 😺
