### ISSUE TITLE
После ~50 удачно добавленных треков из плейлиста возникла ошибка

### ISSUE THREAD

**Issue by Nxdxri** [mewforest/vk-music-import#20]
После отправки ссылки ~50 треков удачно добавляются в плейлист вк, но потом выскакивает ошибка 
ERROR:root:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "vk-music-import.py", line 431, in <module>
  File "vk-music-import.py", line 293, in main
  File "vk_api\vk_api.py", line 684, in method
  File "vk-music-import.py", line 68, in captcha_handler
AttributeError: 'NoneType' object has no attribute 'group'
Нажмите Enter, чтобы завершить работу программы...
Насколько я понимаю это снова из-за капчи. Пытался поменять значение BYPASS_CAPTCHA на 0, но не работает.

Технические данные:
 - ОС Windows 10
 - Содержимое файла настроек на момент последней ошибки 
BYPASS_CAPTCHA="1"
SPOTIFY_MODE="1"
APPLE_MODE="0"
REVERSE="1"
STRICT_SEARCH="0"
ADD_TO_LIBRARY="0"
 - Ссылка на плейлист https://open.spotify.com/playlist/46pltjPk6BjShKHHjHbSFf?si=4b14d45459fc4e8b
 - Ссылка на профиль ВКонтакте https://vk.com/momgethecamera
 -  Запускал готовый релиз
 - Версия программы 0.5

**Comment by Nxdxri** [comment]
Проверил через 5 часов, стало снова выдавать ошибку после 51 трека 
INFO:root:Ищу трек "Bad Guy" от исполнителя Toli Wild (51 из 177)...
ERROR:root:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "vk-music-import.py", line 431, in <module>
  File "vk-music-import.py", line 293, in main
  File "vk_api\vk_api.py", line 684, in method
  File "vk-music-import.py", line 68, in captcha_handler
AttributeError: 'NoneType' object has no attribute 'group'
Нажмите Enter, чтобы завершить работу программы...

**Comment by snowman03** [comment]
```
INFO:root:Ищу трек "Noise" от исполнителя Lastlings (51 из 531)...
ERROR:root:'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "vk-music-import.py", line 431, in <module>
  File "vk-music-import.py", line 293, in main
  File "vk_api\vk_api.py", line 684, in method
  File "vk-music-import.py", line 68, in captcha_handler
AttributeError: 'NoneType' object has no attribute 'group'
```

`BYPASS_CAPTCHA="1"
SPOTIFY_MODE="1"
APPLE_MODE="0"
REVERSE="1"
STRICT_SEARCH="0"
ADD_TO_LIBRARY="0"`

`https://open.spotify.com/playlist/0GoQedvZwO4jaWgtdZXOEs`

0.5 версия под вин.

**Comment by mewforest** [comment]
Всем привет!

Судя по ошибке скрипт не может загрузить капчу. 

Возможно, способ получения капчи у ВК поменялся, оттого и ошибка, буду отлаживать и смотреть, как это пофиксить.

Спасибо, что сообщили 👾

**Comment by mewforest** [comment]
Пофиксил, действительно ссылки от капчи поменялись немного, пришлось немного изменить метод для парсинга.

Скачать обновлённую версию с фиксом можете [здесь](https://github.com/mewforest/vk-music-import/releases/download/0.5/vk-music-import-v0.5_fix1_win32.zip).
