### ISSUE TITLE
[Проблема] установки requirements.txt

### ISSUE THREAD

**Issue by livxbox5** [mewforest/vk-music-import#24]
Я хочу поставить это на termux андроид все поставил и настроел файл 
Но проблема с python (requirements.txt)
Это не ставиться не как
![Screenshot_20231229_162100](https://github.com/mewforest/vk-music-import/assets/76809274/cb496f5e-5d47-4472-9377-88f3a8ced0cf)
![Screenshot_20231229_162316](https://github.com/mewforest/vk-music-import/assets/76809274/3e6bb97f-14d6-45cb-9bdc-651156eb4557)
![Screenshot_20231229_162320](https://github.com/mewforest/vk-music-import/assets/76809274/006fb93e-e258-4b52-8b3b-318e46451ece)
![Screenshot_20231229_162334](https://github.com/mewforest/vk-music-import/assets/76809274/ceaa7e16-78d8-497f-b22d-f2b43df5fa28)

**Comment by mewforest** [comment]
Во-первых, для Termux лучше использовать предыдущую версию - без интерфейса (0.7). Во-вторых, судя по ошибке, вам нужен onnxruntime, нет уверен, что он есть на Андроид (без нее не будет работать автоматическое решение капчи, а ручное использовать на Termux нельзя - там интерфейс открывается). 

С Наступающим!
