### ISSUE TITLE
[Проблема] зависает при поиске музыки

### ISSUE THREAD

**Issue by Sivel0302** [mewforest/vk-music-import#25]
**Опишите проблему**
Стал зависать при поиске музыки после 22 +- добавлений, сама программа не зависает, всё кликается, но в логе пишет только что ищет

**Как воспроизвести ошибку**
Просто импортирую музыку из файла txt и он зависает через 22+- добавления

**Скриншоты**
![image](https://github.com/mewforest/vk-music-import/assets/104088789/a8e0891b-53a7-4f83-91ce-fe3ab49029b3)

**Технические данные (пожалуйста, заполните следующую информацию):**
 - ОС Windows 11
 - Содержимое файла настроек (`.env`)
```
VK_TOKEN='убрано разумеется'
BYPASS_CAPTCHA='1'
SPOTIFY_MODE='0'
APPLE_MODE='0'
VK_LINKS_MODE='0'
REVERSE='1'
STRICT_SEARCH='0'
ADD_TO_LIBRARY='1'
TIMEOUT_AFTER_ERROR='15'
TIMEOUT_AFTER_CAPTCHA='15'
TIMEOUT_AFTER_SUCCESS='15'
```
 - Запускал exe файл
 - Версия программы 1.0 beta

**Дополнительная информация**
Вчера всё ок работало + использовал впн чтобы вк не давал капчи, сейчас же просто стало зависать. При перезапуске и редактирования txt, чтобы не добавлял те что уже добавлены - находит этот трек без проблем

**Comment by mewforest** [comment]
Здравствуйте! А если убрать этот трек, поиск не спотыкается?

**Comment by Sivel0302** [comment]
Снова перезапустил - работает пока что

**Comment by Sivel0302** [comment]
> Здравствуйте! А если убрать этот трек, поиск не спотыкается?

если перезапустить с этим же треком - ищет норм, ща вроде снова всё работает

**Comment by mewforest** [comment]
Значит, это был временный бан на вызов Audio API от VK, vk-music-import тут не при чем 🤷🏻‍♂️ 
Закрываем ветку.
