### ISSUE TITLE
windows app 1.1 can't start

### ISSUE THREAD

**Issue by ekuhtin** [mewforest/vk-music-import#27]
vk-music-import.exe - can't start!
Starting exe file
this window appear

**Технические данные (пожалуйста, заполните следующую информацию):**
Win10
 - Содержимое файла настроек (`.env`)
 - VK_TOKEN=""
BYPASS_CAPTCHA="1"
SPOTIFY_MODE="0"
APPLE_MODE="0"
VK_LINKS_MODE="1"
REVERSE="1"
STRICT_SEARCH="0"
ADD_TO_LIBRARY="0"
TIMEOUT_AFTER_ERROR="1"
TIMEOUT_AFTER_CAPTCHA="0"
TIMEOUT_AFTER_SUCCESS="0"
 - Ссылка на плейлист
 - No
 - Ссылка на профиль ВКонтакте
 - No
 - Запускали ли вы готовый релиз (или использовали Python)?
 - Ready release
 - Версия программы [например, 0.1]
 1.1

![list-err](https://github.com/user-attachments/assets/240b032b-cd0d-4be5-9002-c01b24998593)

**Comment by mewforest** [comment]
@ekuhtin Please, check is Microsoft Visual C++ is installed: https://github.com/microsoft/onnxruntime/issues/16116#issuecomment-1768732885

**Comment by ekuhtin** [comment]
С библиотеками решилось последний - VC_redist.x64.exe скачаный с МС помог.
Теперь зависло с принятием листа из текстового файла

**Comment by ekuhtin** [comment]
Проблема ушла с перенаправлением в профиль или в настроенную группу - открыть там музыку...
