### ISSUE TITLE
[Проблема] Не возвращается список треков (Bad Request)

### ISSUE THREAD

**Issue by LevganSaxen** [mewforest/vk-music-import#4]
**Опишите проблему**
Ошибка 504 Gateway Time Out

**Скриншоты**
![image](https://user-images.githubusercontent.com/47000695/168496051-2678b90a-7106-4915-9c0f-f9750968d27d.png)
**Технические данные (пожалуйста, заполните следующую информацию):**
 - Win 10
 - Содержимое файла настроек (`.env`) Поумолчанию

 - Запускал готовый релиз
 - Версия программы 0ю.2

**Comment by mewforest** [comment]
Здравствуйте!

Проблема в том, что сторонний сервис (https://spotya.ru/), который я использую для получения списка треков из ссылки на плейлист, сейчас [недоступен](https://www.isitdownrightnow.com/spotya.ru.html).

Предлагаю подождать, пока сервис не вернёт свою работоспособность.

**Comment by mewforest** [comment]
Разработчик ([@UmnikOne](https://t.me/UmnikOne)) восстановил работоспособность сервиса, проблема решена 💯
