### ISSUE TITLE
[Проблема] Сохранило 10% треков и сообщило об успешном завершении

### ISSUE THREAD

**Issue by BrokVid** [mewforest/vk-music-import#5]
На скрине в принципе всё видно
![image](https://user-images.githubusercontent.com/23031579/171105072-96947ac9-83dc-4e13-80e7-7b2124095a5f.png)

**Comment by mewforest** [comment]
Музыка из Спотифая или из треклиста? Поделитесь пожалуйста файлом/ссылкой.

**Comment by BrokVid** [comment]
Из треклиста
[tracklist.txt](https://github.com/mewforest/vk-music-import/files/8803230/tracklist.txt)

**Comment by mewforest** [comment]
Дело в том, что ваш треклист без разделителя на исполнителя и название трека. Треклист должен быть такого формата: 

```
Khalid - Better
Billie Eilish - i love you
```

Для вашего файла сделал фикс:  https://pastebin.com/pi92xW8M

P.S. Валидный треклист можно получить из любого музыкального сервиса на [TuneMyMusic](https://www.tunemymusic.com/ru/). Примерную инструкцию о том, как это сделать можно посмотреть [на СберЗвуке](https://zvuk.com/lp/howto).
