### ISSUE TITLE
[v0.4] Отключить создание плейлиста при ADD_TO_LIBRARY="1" по умолчанию

### ISSUE THREAD

**Issue by underwear** [mewforest/vk-music-import#7]
При env `ADD_TO_LIBRARY="1"`, пишет **и** в плейлист, **и** в мои аудиозаписи

```
INFO:root:Нашел похожий трек: "Everyday - Logic, Marshmello" → "Logic, Marshmello - Everyday"
INFO:root:Добавляю "Logic, Marshmello - Everyday" (id: 456559211) в плейлист...
INFO:root:Добавляю "Logic, Marshmello - Everyday" (id: 456559211) в мои аудиозаписи...
INFO:root:Успешно добавил в мои аудиозаписи: "Logic, Marshmello - Everyday"
INFO:root:Успешно добавил в плейлист: "Logic, Marshmello - Everyday"
```

**Comment by mewforest** [comment]
Добрый день! Да, так и есть, это не баг т.к. добавление в мою музыку - дополнительная фича.
Но вы правы, можно добавить возможность отключения создания плейлиста.

**Comment by mewforest** [comment]
Утилита сейчас работает в режиме as-is (как есть), поддержка новых фичей, к сожалению, больше не планируется. 

Сейчас VK часто временно блокирует утилиту когда вы отправляете слишком большое количество запросов на поиск, однако, на добавление треков в плейлист ограничений нет, поэтому, в целом, ничто не мешает удалить плейлисты, если они не нужны.
