### ISSUE TITLE
[Проблема] Добавляется по 2 трека в плейлист

### ISSUE THREAD

**Issue by xtenshhi** [mewforest/vk-music-import#8]
при добавление треков в плейлист треки добавляются 2 раза. В плейлисте спотифи 1300 в приложении показывается что треков 2600. Так же почему-то когда много треков в плейлисте создаётся ещё 1 плейлист после того как в первый добавляется ~900 треков

Все эти баги в новой версии 0.3, в 0.2 всё нормально

**Comment by mewforest** [comment]
Спасибо за сообщение о баге! 
Исправил, треки теперь больше не дублируются.

Изменения пока только в исходном коде, в течение суток обновлю архив с версией для Windows (тогда и закрою issue).

**Comment by mewforest** [comment]
Архив обновлён! Ссылки на скачивание: [релизы](https://github.com/mewforest/vk-music-import/releases/tag/0.3), [telegram-канал](https://t.me/mewnotes/65)
